apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
  namespace: test-ahyeha
spec:
  selector:
    matchLabels:
      app: usermanagement
  replicas: 1
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
        - name: usermanagement
          # enter the path to your image, be sure to include the correct region prefix
          image: jed.ocir.io/axulzqeiw39c/usermanagement:latest
          ports:
            - containerPort: 5055
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=prod,api-docs,no-liquibase -Ddb.name=usermanagement_db -Ddb.port=3306 -Ddb.url=10.10.20.249 -Ddb.user=admin -Ddb.password=2gXpMQ!k6%8E"
      imagePullSecrets:
        # enter the name of the secret you created
        - name: ocirsecretdev

---
apiVersion: v1
kind: Service
metadata:
  name: usermanagements-service
  namespace: test-ahyeha
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5055
  selector:
    app: usermanagement

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usermanagements-ingress-path
  namespace: test-ahyeha
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - "dev.ahyeha.com"
      secretName: apps-tls
  rules:
    - host: "dev.ahyeha.com"
      http:
        paths:
          - path: /usermanagements(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: usermanagements-service
                port:
                  number: 80
