apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql0
  namespace: ai-ems-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 50Gi
  hostPath:
    path: /mysql1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1
  namespace: ai-ems-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 50Gi
  hostPath:
    path: /mysql2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2
  namespace: ai-ems-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 50Gi
  hostPath:
    path: /mysql3
