apiVersion: v1
kind: Service
metadata:
  namespace: dev-ahyeha
  labels:
    app: usermanagement
  name: usermanagement-service
spec:
  clusterIP: None
  ports:
  - port: 80
  selector:
    app: usermanagement

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: usermanagement-set
  namespace: dev-ahyeha
spec:
  serviceName: "usermanagement-service"
  replicas: 2
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      namespace: dev-ahyeha
      labels:
        app: usermanagement
    spec: 
      terminationGracePeriodSeconds: 1800
      containers:
       - name: usermanagement
        image: jed.ocir.io/axulzqeiw39c/usermanagement:_VERSION_  
        ports:
        - containerPort: 5055
      imagePullSecrets: 
       - name: ocirsecretdev  
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20  
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-pass
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-db-usm-url
                key: database
  volumeClaimTemplates:
  - metadata:
      name: mysql-store
      namespace: dev-ahyeha
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: "manual"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usermanagement-ingress-path
  namespace: dev-ahyeha
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - "dev.ahyeha.com"
      secretName: apps-tls
  rules:
    - host: "dev.ahyeha.com"
      http:
        paths:
          - path: /userm(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: usermanagement-service
                port:
                  number: 80
